#!/usr/bin/env python3
"""Create basic human-readable report bundle from checks."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def render_html(payload: dict[str, Any], run_id: str) -> str:
    rows = []
    for check in payload["checks"]:
        rows.append(
            "<tr>"
            f"<td>{check['name']}</td>"
            f"<td>{check['reference']}</td>"
            f"<td>{check['observed']}</td>"
            f"<td>{'PASS' if check['pass'] else 'FAIL'}</td>"
            "</tr>"
        )
    table_rows = "\n".join(rows)
    return (
        "<!DOCTYPE html><html><head><meta charset='utf-8'>"
        f"<title>Reliability Report {run_id}</title></head><body>"
        f"<h1>Reliability Report - {run_id}</h1>"
        f"<p>Summary: {payload['summary']}</p>"
        "<table border='1' cellspacing='0' cellpadding='6'>"
        "<tr><th>Metric</th><th>Reference</th><th>Observed</th><th>Status</th></tr>"
        f"{table_rows}</table></body></html>"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checks", required=True)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args()

    with Path(args.checks).open("r", encoding="utf-8") as handle:
        payload = json.load(handle)

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    html = render_html(payload, args.run_id)
    (out_dir / "index.html").write_text(html, encoding="utf-8")
    (out_dir / "report.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    (out_dir / "README.txt").write_text(
        "Open index.html in any browser. This bundle is generated by scripts/generate_report_bundle.py.\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
